// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCpzS5JaBDzZz9Zit7X6ILQZ47LXiENAQ',
    appId: '1:356708239119:web:7f4e420eaa7e843984207a',
    messagingSenderId: '356708239119',
    projectId: 'coupling-c9fba',
    authDomain: 'coupling-c9fba.firebaseapp.com',
    storageBucket: 'coupling-c9fba.appspot.com',
    measurementId: 'G-2NDPGMNJRM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJtiaWJhcs8aZkempeATQxYToNkVZmm7k',
    appId: '1:356708239119:android:e90e77ac7247d66a84207a',
    messagingSenderId: '356708239119',
    projectId: 'coupling-c9fba',
    storageBucket: 'coupling-c9fba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSCuHQyHuF7g9Er-XMxkul1m3XO_g7J8o',
    appId: '1:356708239119:ios:fe731afed81df24e84207a',
    messagingSenderId: '356708239119',
    projectId: 'coupling-c9fba',
    storageBucket: 'coupling-c9fba.appspot.com',
    androidClientId: '356708239119-joscqme591r9p2ke92090qjssgfkkted.apps.googleusercontent.com',
    iosClientId: '356708239119-irnnjovpl5sioo838ll9ke869g1ub11j.apps.googleusercontent.com',
    iosBundleId: 'com.hj.coupling',
  );
}
